DATABASE_host : 'localhost'
DATABASE_port : '3306'
DATABASE_db : 'crypto'
DATABASE_user : 'userforberlintest'
DATABASE_pass : 'passforberlintest'
DATABASE_table : 'cryptocurrency_lake'

example_coins : 'GAT,GAL'

API_token : 'MKvR8WPypXZ1NOcLnDJjsHfhEHaJGN'

name_app : 'Test_project_berlin'