DATABASE_host : 'localhost'
DATABASE_port : '3306'
DATABASE_db : 'crypto'
DATABASE_user : 'alaiza_projects'
DATABASE_pass : 'alaiza_projects2'
DATABASE_table : 'cryptocurrency_lake'

EMAIL_api_key : '0be99a2ae46677b36f8c946b895e6a40'
EMAIL_secret_key : 'f03498c3d66cb640bc86f19b60eb6ebb'
EMAIL_version : 'v3.1'

API_token : 'MKvR8WPypXZ1NOcLnDJjsHfhEHaJGN'

name_app : 'Test_project_berlin'