version: 1

formatters:
    simple:
        format: "%(levelname)s - %(asctime)s - %(threadName)s - %(name)s : Line #%(lineno)d -- %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: logs/basic-stats-reports.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: simple
        filename: logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    pyhive:
        level: INFO
        handlers: [info_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console]